import type { Metadata } from 'next'
import { Anton, Poppins } from 'next/font/google'
import './globals.css'

import Logo from '@/src/shared/Logo/Logo'
import { StoreProvider } from '@/src/components/StoreProvider/StoreProvider'
import LoadingProvider from '@/src/components/LoadingProvider/LoadingProvider'
import TrackingScript from '@/src/components/TrackingScript'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const anton = Anton({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-anton',
  display: 'swap',
})

const poppins = Poppins({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-poppins',
  display: 'swap',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <TrackingScript />

      <body className={`${anton.variable} ${poppins.variable} antialiased font-poppins`}>
        <StoreProvider>
          <LoadingProvider>
            <Logo />
            {children}
          </LoadingProvider>
        </StoreProvider>
      </body>
    </html>
  )
}
